Rework console dot's repository to something real
jelly/console.dot pull request #3
Opened 2022-09-06 16:27 UTC by jelly

@martinpitt FYI

2022-09-07 09:13 UTC, martinpitt commented on multiplexer.py
> +location /session/{sessionid} {{
location /api/cockpit-9090/session/{sessionid} {{

2022-09-07 15:24 UTC, martinpitt commented
This is my current state: I can register two sessions, run two VMs, look up the random host port mapping in `sudo podman ps`, attach websocat/bridge in the VMs to the random host ports, and get two cockpit sessions on the session paths like https://localhost:8443/api/cockpit-9090/session/726d844e-ba10-4134-9a96-b846e42e90cb/ .

Problems:
 - Calling that URL without a trailing slash triggers an assertion in cockpit-ws
 - Creating the second session damaged the first one: I get "not a teapot" for all pages on the first session. This is a simple bug in the multiplexer, it does not write `location` stanzas for the old sessions, only the new one.

```diff
--- multiplexer.py
+++ multiplexer.py
@@ -76,6 +76,7 @@ class ProxyHTTPRequestHandler(BaseHTTPRequestHandler):
         print(self.path)
         if self.path == "/register":
             sessionid = str(uuid.uuid4())
+            # sessionid = "123"
             name = f'session-{sessionid}'
             connection = http.client.HTTPConnection('localhost')
             connection.sock = socket.socket(socket.AF_UNIX)
@@ -83,7 +84,9 @@ class ProxyHTTPRequestHandler(BaseHTTPRequestHandler):
             body = {
                     'image': 'quay.io/rhn_engineering_mpitt/ws',
                     'name': name,
-                    'command': ['sleep', 'infinity'],
+                    #'command': ['sleep', 'infinity'],
+                    'command': ['sh', '-exc', f"printf '[Webservice]\nUrlRoot=/api/cockpit-9090/session/{sessionid}/\\nWebsocketRoot=/wss/cockpit-9090/session/{sessionid}/\\nOrigins = https://localhost:8443\\n' > /etc/cockpit/cockpit.conf; exec /usr/libexec/cockpit-ws --for-tls-proxy --local-session=socat-session.sh"],
+                    'portmappings': [{ 'container_port': 8080}],
                     'remove': True,
                     'Networks': {'consoledot': {}},
             }
@@ -100,8 +103,52 @@ class ProxyHTTPRequestHandler(BaseHTTPRequestHandler):
 
             for sessionid in SESSIONS:
                 routes = f"""
-location /session/{sessionid} {{
-    proxy_pass http://session-{sessionid}:9090/api/cockpit-9090/{sessionid};
+location /api/cockpit-9090/session/{sessionid} {{
+    proxy_pass http://session-{sessionid}:9090/api/cockpit-9090/session/{sessionid};
+    # Don't pass on proxy auth
+    proxy_set_header Authorization "";
+
+    # Required to proxy the connection to Cockpit
+    proxy_set_header Host $host;
+    proxy_set_header X-Forwarded-Proto $scheme;
+
+    # Pass ETag header from Cockpit to clients.
+    # See: https://github.com/cockpit-project/cockpit/issues/5239
+    gzip off;
+}}
+location /wss/cockpit-9090/session/{sessionid} {{
+    proxy_pass http://session-{sessionid}:9090/wss/cockpit-9090/session/{sessionid};
+
+    # Required to proxy the connection to Cockpit
+    proxy_set_header Host $host;
+    proxy_set_header X-Forwarded-Proto $scheme;
+
+    # Required for web sockets to function
+    proxy_http_version 1.1;
+    proxy_buffering off;
+    proxy_set_header Upgrade $http_upgrade;
+    proxy_set_header Connection "upgrade";
+
+    # Pass ETag header from Cockpit to clients.
+    # See: https://github.com/cockpit-project/cockpit/issues/5239
+    gzip off;
+}}
+location /wss/cockpit-8080/session/{sessionid} {{
+    proxy_pass http://session-{sessionid}:8080/wss/cockpit-8080/session/{sessionid};
+
+    # Required to proxy the connection to Cockpit
+    proxy_set_header Host $host;
+    proxy_set_header X-Forwarded-Proto $scheme;
+
+    # Required for web sockets to function
+    proxy_http_version 1.1;
+    proxy_buffering off;
+    proxy_set_header Upgrade $http_upgrade;
+    proxy_set_header Connection "upgrade";
+
+    # Pass ETag header from Cockpit to clients.
+    # See: https://github.com/cockpit-project/cockpit/issues/5239
+    gzip off;
 }}
     """
             open('/etc/nginx/nginx.conf', 'w').write(NGINX_TEMPLATE.format(routes=routes))

```

2022-09-08 14:04 UTC, martinpitt requested changes

2022-09-08 14:04 UTC, martinpitt commented on Makefile
> +	podman run --network $(NETWORK) --rm -p $(PORT):443 $(CONTAINER_NAME)
what is CONTAINER_NAME here? also, shouldn't that run podman play kube etc?

2022-09-08 14:04 UTC, martinpitt commented on Makefile
> +	podman run --name multiplexer --network $(NETWORK) -d --rm -ti -p $(PORT):443 -v /run/podman/podman.sock:/run/podman/podman.sock -v $(PWD):/app $(CONTAINER_NAME) sleep infinity
Is that still relevant?

2022-09-08 14:04 UTC, martinpitt commented on appservice/multiplexer.py
> +Only system containers!
Not any more! :stuck_out_tongue_winking_eye:

2022-09-08 14:04 UTC, martinpitt commented on kube.yml
> +---
Let's name it "webconsoledot-local.yaml" or so?

2022-09-08 14:04 UTC, martinpitt commented on kube.yml
> +        path: /run/user/1000/podman/podman.sock
Hardcoding 1000 is "ugh", but let's fix that later.

2022-09-08 14:04 UTC, martinpitt commented on multiplexer.py
> +import os
We have this twice

2022-09-08 14:48 UTC, jelly commented on Makefile
> +	podman network create $(NETWORK)
I'd like to do that, but I can't remove a network if the pod is still around. So I'll settle with `network create || true` as podman play kube foo.yml --down does not remove anything

2022-09-08 14:50 UTC, jelly commented on kube.yml
> +      image: docker.io/redis:7.0.4
Sure, but that mind be bound to change.

2022-09-08 15:48 UTC, martinpitt requested changes

2022-09-08 15:48 UTC, martinpitt commented on Makefile
> +	podman network rm -t0 -f $(NETWORK)
--long --options please

2022-09-08 15:58 UTC, martinpitt approved these changes
Dankjewel!

2022-09-08 15:58 UTC, merged